# version format
version: 2.0.0.{build}

# Do not build on tags
skip_tags: true


build_script:
  - cd Build
  - Package.build.cmd

artifacts:
  - path: Releases\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: LMGP8EWGJSisyUMJkBHPK65kEaSGr1hgsurS4vp1hhEAMYazvL+ioLSZ2Qk/0xHZ
  artifact: /.*\.nupkg/
